version: "3.9"

services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb_${PHP_VERSION}
    image: mariadb:${MARIADB_VERSION}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-app}
    volumes:
      - ./db/mariadb:/var/lib/mysql:rw
    networks:
      - localhost_network

  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php_${PHP_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ..:${APPLICATION_PATH}
    env_file: .env
    working_dir: ${APPLICATION_PATH}
    networks:
      - localhost_network
    depends_on:
      - mariadb

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx_${NGINX_VERSION}
    image: nginx:${NGINX_VERSION}
    volumes:
      - ..:${APPLICATION_PATH}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    env_file: .env
    working_dir: ${APPLICATION_PATH}
    networks:
      - localhost_network
    depends_on:
      - mariadb
      - php

  node:
    container_name: ${COMPOSE_PROJECT_NAME}_node_${NODE_VERSION}
    image: node:${NODE_VERSION}
    env_file: .env
    volumes:
      - ..:${APPLICATION_PATH}
    working_dir: ${APPLICATION_PATH}
    command: ["node", "server.js"]
    networks:
      - localhost_network
    depends_on:
      - mariadb
      - php
      - nginx

networks:
  localhost_network:
    driver: bridge
